baseURL: http://snehmehta.dev/
languageCode: en-us
title: Sneh Mehta
theme: "PaperMod"

params:
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: true
    images: ["papermod-cover.png"]


    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archive
              url: "/archive"
            - name: Github
              url: "https://github.com/"

    homeInfoParams:
        Title: "Hi there! 👋"
        Content: >
            Welcome I'll be documenting my journey over this site.
            
    socialIcons:
        - name: Github
          url: "https://github.com/snehmehta"
        - name: RSS
          url: "index.xml"


menu:
    main:
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 10
        - identifier: post
          name: Blog
          url: /post/
          weight: 20       
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 30       
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 40

        
