baseURL: http://snehmehta.vercel.app/
languageCode: en-us
title: Sneh Mehta
theme: "PaperMod"

params:
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]


    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hi there! "
        Content: >
            Welcome I'll be documenting my journey over this site.
            
    socialIcons:
        - name: Github
          url: "https://github.com/snehmehta"
        - name: RSS
          url: "index.xml"


menu:
    main:
        - identifier: projects
          name: Projects
          url: /tags/
          weight: 10
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        
