baseURL: https://snehmehta.dev/
languageCode: en-us
title: Sneh Mehta
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
    env: production
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: true
    defaultTheme: light
    ShowShareButtons: true
    ShowReadingTime: true
    ShowPostNavLinks: true
    disableThemeToggle: true

    
    
    images: ["papermod-cover.png"]


    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archive
              url: "/archive"
            - name: Github
              url: "https://github.com/"

    homeInfoParams:
        Title: "Hi there! 👋"
        Content: >
            Welcome, I'll be documenting my journey over this site.
            
    socialIcons:
        - name: Github
          url: "https://github.com/snehmehta"
        - name: RSS
          url: "index.xml"

    header:
      avatar: avatar.jpg
      contact: true
      tagline: true
      links: false

    pages:
      - features:
          - feature: about
            title: About Me
          - feature: experience
      - features:
          - feature: projects
            collection: projects
          - feature: awards
          - feature: certificates
            title: Certifications
          # - feature: interests
          #   widget: word-list
          #   style: list

    side:
      - feature: skills
        widget: word-list
        style: compact # list, compact, title-list
      - feature: education
      - feature: interests
        widget: word-list
        style: list


menu:
    main:
        - identifier: projects
          name: Projects
          url: /projects/
          weight: 10
        - identifier: post
          name: Blog
          url: /post/
          weight: 20       
             
        - identifier: resume
          name: Resume
          url: /resume/
          weight: 30

        - identifier: search
          name: Search
          url: /search/
          weight: 40  

        
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary